namespace LFSDriftBuddy.InSim
{
        public enum PacketType : byte
    {
        ISP_NONE = 0,
        ISP_ISI = 1,
        ISP_VER = 2,
        ISP_TINY = 3,
        ISP_SMALL = 4,
        ISP_STA = 5,
        ISP_SCH = 6,
        ISP_SFP = 7,
        ISP_SCC = 8,
        ISP_CPP = 9,
        ISP_ISM = 10,
        ISP_MSO = 11,
        ISP_III = 12,
        ISP_MST = 13,
        ISP_MTC = 14,
        ISP_MOD = 15,
        ISP_VTN = 16,
        ISP_RST = 17,
        ISP_NCN = 18,
        ISP_CNL = 19,
        ISP_CPR = 20,
        ISP_NPL = 21,
        ISP_PLP = 22,
        ISP_PLL = 23,
        ISP_LAP = 24,
        ISP_SPX = 25,
        ISP_PIT = 26,
        ISP_PSF = 27,
        ISP_PLA = 28,
        ISP_CCH = 29,
        ISP_PEN = 30,
        ISP_TOC = 31,
        ISP_FLG = 32,
        ISP_PFL = 33,
        ISP_FIN = 34,
        ISP_RES = 35,
        ISP_REO = 36,
        ISP_NLP = 37,
        ISP_MCI = 38,
        ISP_MSX = 39,
        ISP_MSL = 40,
        ISP_CRS = 41,
        ISP_BFN = 42,
        ISP_AXI = 43,
        ISP_AXO = 44,
        ISP_BTN = 45,
        ISP_BTC = 46,
        ISP_BTT = 47,
        ISP_RIP = 48,
        ISP_SSH = 49,
        ISP_CON = 50,
        ISP_OBH = 51,
        ISP_HLV = 52,
        ISP_PLC = 53,
        ISP_AXM = 54,
        ISP_ACR = 55,
        ISP_HCP = 56,
        ISP_NCI = 57,
        ISP_JRR = 58,
        ISP_UCO = 59,
        ISP_OCO = 60,
        ISP_TTC = 61,
        ISP_SLC = 62,
        ISP_CSC = 63,
        ISP_CIM = 64,
        ISP_MAL = 65,
        ISP_PLH = 66,
        ISP_IPB = 67,
    }

        public enum TinyType : byte
    {
        TINY_NONE = 0,
        TINY_VER = 1,
        TINY_CLOSE = 2,
        TINY_PING = 3,
        TINY_REPLY = 4,
        TINY_VTC = 5,
        TINY_SCP = 6,
        TINY_SST = 7,
        TINY_GTH = 8,
        TINY_MPE = 9,
        TINY_ISM = 10,
        TINY_REN = 11,
        TINY_CLR = 12,
        TINY_NCN = 13,
        TINY_NPL = 14,
        TINY_RES = 15,
        TINY_NLP = 16,
        TINY_MCI = 17,
        TINY_REO = 18,
        TINY_RST = 19,
        TINY_AXI = 20,
        TINY_AXC = 21,
        TINY_RIP = 22,
        TINY_NCI = 23,
        TINY_ALC = 24,
        TINY_AXM = 25,
        TINY_SLC = 26,
        TINY_MAL = 27,
        TINY_PLH = 28,
        TINY_IPB = 29,
    }

    [System.Flags]
    public enum StateFlags : ushort
    {
        ISS_GAME = 1,
        ISS_REPLAY = 2,
        ISS_PAUSED = 4,
        ISS_SHIFTU = 8,
        ISS_SHIFTU_FOLLOW = 16,
        ISS_SHIFTU_NO_OPT = 32,
        ISS_SHOW_2D = 64,
        ISS_FRONT_END = 128,
        ISS_MULTI = 256,
        ISS_MPSPEEDUP = 512,
        ISS_WINDOWED = 1024,
        ISS_SOUND_MUTE = 2048,
        ISS_VIEW_OVERRIDE = 4096,
        ISS_VISIBLE = 8192,
        ISS_TEXT_ENTRY = 16384,
    }

        public enum ISFlags : ushort
    {
        ISF_RES_0 = 1,
        ISF_RES_1 = 2,
        ISF_LOCAL = 4,
        ISF_MSO_COLS = 8,
        ISF_NLP = 16,
        ISF_MCI = 32,
        ISF_CON = 64,
        ISF_OBH = 128,
        ISF_HLV = 256,
        ISF_AXM_LOAD = 512,
        ISF_AXM_EDIT = 1024,
        ISF_REQ_JOIN = 2048,
    }

        public enum ButtonStyle : byte
    {
        ISB_C1 = 1,
        ISB_C2 = 2,
        ISB_C4 = 4,
        ISB_CLICK = 7,
        ISB_LIGHT = 8,
        ISB_DARK = 16,
        ISB_LEFT = 32,
        ISB_RIGHT = 64,
    }
}