<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>LFSDriftTools</AssemblyName>
    <RootNamespace>LFSDriftTools</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
	<Version>0.289.0821</Version>
	<AssemblyVersion>0.289.0821.0</AssemblyVersion>
	<FileVersion>0.289.0821.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LayeredForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="app.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\active.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\active.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\idle.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="indicator_cancel.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="indicator_click.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\indicator_cancel.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\indicator_click.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\indicator_click_off.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\indicator_click_on.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
